spring:
  datasource:
    username: root
    password: lixc04260611
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.42.14.67:3306/springboot_mybatisplus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
#   执行DDL
    schema:
      - classpath:schema-mysql.sql
#    执行DML
#    data:
#      - classpath:data-mysql.sql
    initialization-mode: always
#    数据库初始化模式（执行DDL和DML） 设置为always


#    initialSize: 1
#    minIdle: 3
#    maxActive: 20
#    # 配置获取连接等待超时的时间
#    maxWait: 60000
#    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#    timeBetweenEvictionRunsMillis: 60000
#    # 配置一个连接在池中最小生存的时间，单位是毫秒
#    minEvictableIdleTimeMillis: 30000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    # 打开PSCache，并且指定每个连接上PSCache的大小
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 20
#    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
#    filters: stat,wall,slf4j
#    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    # 合并多个DruidDataSource的监控数据
#        #useGlobalDataSourceStat: true

mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8090