spring:
  datasource:
    username: root
    password: lixc04260611
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://121.42.14.67:3306/springboot_mybatisplus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/springboot_mybatisplus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

    type: com.alibaba.druid.pool.DruidDataSource
#   执行DDL
    schema:
      - classpath:schema-mysql.sql

#    执行DML
#    data:
#      - classpath:data-mysql.sql

#    数据库初始化模式（执行DDL和DML） 设置为always
    initialization-mode: always
